### ISSUE TITLE
Incredibly helpful

### ISSUE THREAD

**Issue by Irislucent** [Say-Hello2y/Transformer-attention#1]
非常详细非常有用的推导，没有你我做不出作业qwq
顺便想问问这么多矩阵微分的技巧是在哪里学的

**Comment by Say-Hello2y** [comment]
可以看我知乎文章的参考文献，系统学习的话推荐张贤达老师的矩阵分析与应用



发自我的iPhone


------------------ Original ------------------
From: Yuxuan Wu ***@***.***&gt;
Date: Wed,Nov 15,2023 7:21 AM
To: Say-Hello2y/Transformer-attention ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Say-Hello2y/Transformer-attention] Incredibly helpful (Issue #1)





 
非常详细非常有用的推导，没有你我做不出作业qwq
 顺便想问问这么多矩阵微分的技巧是在哪里学的
